version: '3.7'

services:
  todos:
    container_name: todos
    build:
      context: .
      dockerfile: ./apps/todos/Dockerfile
      target: development
    command: npm run start:dev
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4000:4000
    depends_on:
      - postgres
      - rabbitmq
      # - redis
      # - auth
  notification:
    build:
      context: .
      dockerfile: ./apps/notification/Dockerfile
      target: development
    command: npm run start:dev notification
    env_file:
      - ./apps/notification/.env
    depends_on:
      - postgres
      - rabbitmq
      # - redis
      # - auth
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  # redis:
  #   container_name: redis
  #   image: redis:5
  #   networks:
  #     - webnet
  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data
volumes:
  docker-nest-postgres:
  redis:
    driver: local
# services:
#   todos:
#     build:
#       context: .
#       dockerfile: ./apps/todos/Dockerfile
#       target: development
#     command: npm run start:dev
#     env_file:
#       - .env
#       - ./apps/todos/.env
#     depends_on:
#       - postgres
#       # - billing
#       # - auth
#       # - rabbitmq
#     volumes:
#       - .:/usr/src/app
#       - /usr/src/app/node_modules
#     ports:
#       - '4000:4000'
#   postgres:
#     image: postgres:latest
#     container_name: postgres
#     restart: always
#     env_file:
#       - .env
#     # environment:
#     #   - POSTGRES_USER=postgres
#     #   - POSTGRES_PASSWORD=test123
#     #   - POSTGRES_DB=nest-todo-app
#     volumes:
#       - db:/var/lib/postgresql/data
#     ports:
#       - '5432:5432'

# volumes:
#   db:
#     driver: local
