import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Form from '../components/Form';
import Todos from '../components/Todos';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="container">
          <Form />
          <Todos />
        </div>
      </main>
    </div>
  );
};

export default Home;
